// Courseware Studio LMS-Embedded AI Learning Assistant Widget — Update 326 accessibility hardening
(function () {
  'use strict'
  var EN = window.__CS_AI_TUTOR_ENABLED__
  if (EN === 0 || EN === false || EN === '0') return
  var CFG = window.__CS_AI_TUTOR_CONFIG__ || null
  if (!CFG) return

  var MAX_HISTORY_EXCHANGES = 10
  var SS_KEY_HISTORY = 'cs_ai_tutor_history_v5'
  var SS_KEY_WELCOMED = 'cs_ai_tutor_welcomed_v5'
  var DEFAULT_MATCH_THRESHOLD = 0.52
  var DEFAULT_ANSWER_WEIGHT = 0.30
  var EXACT_PHRASE_BOOST = 0.25
  var PHRASE_TERM_BOOST = 0.10
  var PHRASE_TERM_BOOST_CAP = 0.25
  var MODULE_BOOST_CURRENT = 0.03
  var MODULE_PENALTY_FUTURE = 0.01
  var LESSON_BOOST = 0.02

  var DOM = { button:'cs-tutor-button', panel:'cs-tutor-panel', overlay:'cs-tutor-overlay', title:'cs-tutor-title', closeBtn:'cs-tutor-close', log:'cs-tutor-log', form:'cs-tutor-form', input:'cs-tutor-input', submit:'cs-tutor-submit', status:'cs-tutor-status', moduleToggle:'cs-tutor-module-toggle', welcome:'cs-tutor-welcome', welcomeOk:'cs-tutor-welcome-ok' }

  var LANG = {
    english: { accent:false, stem:true, stop: words('the a an is are was were be been being and or but if then of to in on at by for with do does did have has had what which who when where why how this that these those you your my me we us our it its they them their can could would should will shall as from about into than so not nor too very just only also still even any some all every most more less few many much one two three first second next above below between through during before after up down out off here there tell explain describe show list give provide know want need make please using use used uses become becomes lets') },
    spanish: { accent:true, stem:false, stop: words('el la los las un una unos unas es son fue fueron ser estar esta este de del al a en con por para y o pero si entonces que cual quien cuando donde porque como esto eso estos esas usted ustedes tu tus su sus nuestro nuestra nuestros nuestras se lo le les me mi mis nos muy mas menos tambien solo sobre entre antes despues aqui alli explicar describir mostrar listar dar proporcionar usar usa usado usos') },
    french: { accent:true, stem:false, stop: words('le la les un une des est sont etre avoir a au aux de du en dans avec pour par et ou mais si alors que quel quelle quels quelles qui quand ou pourquoi comment ce cet cette ces vous votre vos tu ton tes son ses nous notre nos il elle ils elles se me mon mes tres plus moins aussi seulement sur entre avant apres ici expliquer decrire montrer lister donner fournir utiliser utilise') },
    german: { accent:true, stem:false, stop: words('der die das den dem des ein eine einer eines einen ist sind war waren sein haben hat hatte und oder aber wenn dann was welche welcher welches wer wann wo warum wie dies diese dieser dieses sie du ihr ihre unser unsere im in am an auf mit fuer von zu als aus ueber unter zwischen vor nach hier dort bitte erklaere beschreibe zeige liste gib verwenden verwendet') },
    portuguese: { accent:true, stem:false, stop: words('o a os as um uma uns umas e ou mas se entao que qual quais quem quando onde porque como este esta estes estas esse essa esses essas de do da dos das em no na nos nas com por para seu sua seus suas meu minha meus minhas nosso nossa nossos nossas voce voces muito mais menos tambem apenas sobre entre antes depois aqui ali explicar descrever mostrar listar dar fornecer usar usa usado') },
    italian: { accent:true, stem:false, stop: words('il lo la i gli le un una uno e o ma se allora che quale quali chi quando dove perche come questo questa questi queste quello quella quelli quelle di del della dei degli delle in nel nella con per da a su tra fra prima dopo qui li tu tuo tua tuoi suo sua noi nostro nostra voi vostro vostra molto piu meno anche solo spiegare descrivere mostrare elencare dare fornire usare usa usato') },
    dutch: { accent:true, stem:false, stop: words('de het een en of maar als dan wat welke wie wanneer waar waarom hoe dit deze dat die jij je jouw u uw wij ons onze zij hun haar is zijn was waren worden hebben heeft had in op aan met voor van naar uit over onder tussen voor na hier daar leg uit beschrijf toon lijst geef gebruik gebruikt gebruiken') }
  }

  var STRINGS = {
    english: { askTutor:'Ask Tutor', title:'LMS-Embedded AI Learning Assistant', openTutor:'Open LMS-Embedded AI Learning Assistant', closeTutor:'Close LMS-Embedded AI Learning Assistant', searchCurrentModuleOnly:'Search current module only', inputPlaceholder:'Ask a question about this course...', inputLabel:'Your question', ask:'Ask', loading:'Loading course Q&A...', loadingWait:'The LMS-Embedded AI Learning Assistant is still loading. Please wait a moment.', refusal:'I could not find a reliable answer for that in the course content. Please refer to the course materials or contact your instructor for help with this topic.', footer:'Runs offline. Verify important answers with your instructor.', welcomeTitle:'Welcome to the LMS-Embedded AI Learning Assistant', welcomeBody:'Ask me about anything covered in this course. I search a curated knowledge base bundled with the course, and your questions stay on your device. AI can make mistakes or miss details, so please verify important answers with your instructor or the official course materials.', gotIt:'Got it', fromModule:'From Module', laterInCourse:'This is covered in more depth later in the course.', earlierInCourse:'You have already covered this earlier in the course.', unavailablePrefix:'LMS-Embedded AI Learning Assistant unavailable' },
    spanish: { askTutor:'Preguntar al tutor', title:'Tutor de IA', openTutor:'Abrir el tutor de IA', closeTutor:'Cerrar el tutor de IA', searchCurrentModuleOnly:'Buscar solo en el módulo actual', inputPlaceholder:'Haz una pregunta sobre este curso...', inputLabel:'Tu pregunta', ask:'Preguntar', loading:'Cargando preguntas y respuestas del curso...', loadingWait:'El tutor de IA todavía se está cargando. Espera un momento.', refusal:'No pude encontrar una respuesta confiable para eso en el contenido del curso. Consulta los materiales del curso o comunícate con tu instructor para obtener ayuda con este tema.', footer:'Funciona sin conexión. Verifica las respuestas importantes con tu instructor.', welcomeTitle:'Bienvenido a tu tutor de IA', welcomeBody:'Pregúntame sobre cualquier tema cubierto en este curso. Busco en una base de conocimientos incluida con el curso, y tus preguntas permanecen en tu dispositivo. La IA puede cometer errores u omitir detalles, así que verifica las respuestas importantes con tu instructor o con los materiales oficiales del curso.', gotIt:'Entendido', fromModule:'Del módulo', laterInCourse:'Esto se cubre con más detalle más adelante en el curso.', earlierInCourse:'Ya cubriste esto anteriormente en el curso.', unavailablePrefix:'Tutor de IA no disponible' },
    french: { askTutor:'Demander au tuteur', title:'Tuteur IA', openTutor:'Ouvrir le tuteur IA', closeTutor:'Fermer le tuteur IA', searchCurrentModuleOnly:'Rechercher uniquement dans le module actuel', inputPlaceholder:'Posez une question sur ce cours...', inputLabel:'Votre question', ask:'Demander', loading:'Chargement des questions-réponses du cours...', loadingWait:'Le tuteur IA est encore en cours de chargement. Veuillez patienter un instant.', refusal:'Je n’ai pas trouvé de réponse fiable à cette question dans le contenu du cours. Consultez les supports du cours ou demandez de l’aide à votre formateur.', footer:'Fonctionne hors ligne. Vérifiez les réponses importantes avec votre formateur.', welcomeTitle:'Bienvenue dans votre tuteur IA', welcomeBody:'Posez-moi des questions sur tout ce qui est couvert dans ce cours. Je recherche dans une base de connaissances incluse avec le cours, et vos questions restent sur votre appareil. L’IA peut faire des erreurs ou manquer des détails. Vérifiez donc les réponses importantes avec votre formateur ou les supports officiels du cours.', gotIt:'Compris', fromModule:'Du module', laterInCourse:'Ce point est traité plus en détail plus tard dans le cours.', earlierInCourse:'Vous avez déjà traité ce point plus tôt dans le cours.', unavailablePrefix:'Tuteur IA indisponible' },
    german: { askTutor:'Tutor fragen', title:'KI-Tutor', openTutor:'KI-Tutor öffnen', closeTutor:'KI-Tutor schließen', searchCurrentModuleOnly:'Nur im aktuellen Modul suchen', inputPlaceholder:'Stellen Sie eine Frage zu diesem Kurs...', inputLabel:'Ihre Frage', ask:'Fragen', loading:'Kurs-Fragen und -Antworten werden geladen...', loadingWait:'Der KI-Tutor wird noch geladen. Bitte warten Sie einen Moment.', refusal:'Ich konnte im Kursinhalt keine verlässliche Antwort darauf finden. Bitte prüfen Sie die Kursmaterialien oder wenden Sie sich an Ihren Trainer.', footer:'Funktioniert offline. Prüfen Sie wichtige Antworten mit Ihrem Trainer.', welcomeTitle:'Willkommen bei Ihrem KI-Tutor', welcomeBody:'Fragen Sie mich zu allem, was in diesem Kurs behandelt wird. Ich suche in einer Wissensbasis, die mit dem Kurs gebündelt ist, und Ihre Fragen bleiben auf Ihrem Gerät. KI kann Fehler machen oder Details übersehen. Prüfen Sie wichtige Antworten daher mit Ihrem Trainer oder den offiziellen Kursmaterialien.', gotIt:'Verstanden', fromModule:'Aus Modul', laterInCourse:'Dies wird später im Kurs ausführlicher behandelt.', earlierInCourse:'Sie haben dies bereits früher im Kurs behandelt.', unavailablePrefix:'KI-Tutor nicht verfügbar' },
    portuguese: { askTutor:'Perguntar ao tutor', title:'Tutor de IA', openTutor:'Abrir o tutor de IA', closeTutor:'Fechar o tutor de IA', searchCurrentModuleOnly:'Pesquisar apenas no módulo atual', inputPlaceholder:'Faça uma pergunta sobre este curso...', inputLabel:'Sua pergunta', ask:'Perguntar', loading:'Carregando perguntas e respostas do curso...', loadingWait:'O tutor de IA ainda está carregando. Aguarde um momento.', refusal:'Não encontrei uma resposta confiável para isso no conteúdo do curso. Consulte os materiais do curso ou fale com seu instrutor para obter ajuda sobre este tópico.', footer:'Funciona offline. Verifique respostas importantes com seu instrutor.', welcomeTitle:'Bem-vindo ao seu tutor de IA', welcomeBody:'Pergunte sobre qualquer conteúdo abordado neste curso. Eu pesquiso em uma base de conhecimento incluída com o curso, e suas perguntas permanecem no seu dispositivo. A IA pode cometer erros ou deixar passar detalhes, portanto verifique respostas importantes com seu instrutor ou com os materiais oficiais do curso.', gotIt:'Entendi', fromModule:'Do módulo', laterInCourse:'Isso é abordado com mais detalhes posteriormente no curso.', earlierInCourse:'Você já viu isso anteriormente no curso.', unavailablePrefix:'Tutor de IA indisponível' },
    italian: { askTutor:'Chiedi al tutor', title:'Tutor IA', openTutor:'Apri il tutor IA', closeTutor:'Chiudi il tutor IA', searchCurrentModuleOnly:'Cerca solo nel modulo corrente', inputPlaceholder:'Fai una domanda su questo corso...', inputLabel:'La tua domanda', ask:'Chiedi', loading:'Caricamento delle domande e risposte del corso...', loadingWait:'Il tutor IA si sta ancora caricando. Attendi un momento.', refusal:'Non ho trovato una risposta affidabile a questa domanda nel contenuto del corso. Consulta i materiali del corso o chiedi aiuto al tuo istruttore.', footer:'Funziona offline. Verifica le risposte importanti con il tuo istruttore.', welcomeTitle:'Benvenuto nel tuo tutor IA', welcomeBody:'Fammi domande su qualsiasi argomento trattato in questo corso. Cerco in una base di conoscenza inclusa nel corso, e le tue domande restano sul tuo dispositivo. L’IA può commettere errori o perdere dettagli, quindi verifica le risposte importanti con il tuo istruttore o con i materiali ufficiali del corso.', gotIt:'Capito', fromModule:'Dal modulo', laterInCourse:'Questo argomento viene trattato in modo più dettagliato più avanti nel corso.', earlierInCourse:'Hai già trattato questo argomento in precedenza nel corso.', unavailablePrefix:'Tutor IA non disponibile' },
    dutch: { askTutor:'Vraag tutor', title:'AI-tutor', openTutor:'AI-tutor openen', closeTutor:'AI-tutor sluiten', searchCurrentModuleOnly:'Alleen huidige module doorzoeken', inputPlaceholder:'Stel een vraag over deze cursus...', inputLabel:'Je vraag', ask:'Vragen', loading:'Cursusvragen en antwoorden laden...', loadingWait:'De AI-tutor wordt nog geladen. Wacht even.', refusal:'Ik kon hiervoor geen betrouwbaar antwoord vinden in de cursusinhoud. Raadpleeg het cursusmateriaal of vraag je instructeur om hulp bij dit onderwerp.', footer:'Werkt offline. Controleer belangrijke antwoorden met je instructeur.', welcomeTitle:'Welkom bij je AI-tutor', welcomeBody:'Stel me vragen over alles wat in deze cursus wordt behandeld. Ik zoek in een kennisbank die met de cursus is meegeleverd, en je vragen blijven op je apparaat. AI kan fouten maken of details missen, dus controleer belangrijke antwoorden met je instructeur of het officiële cursusmateriaal.', gotIt:'Begrepen', fromModule:'Uit module', laterInCourse:'Dit wordt later in de cursus uitgebreider behandeld.', earlierInCourse:'Je hebt dit eerder in de cursus al behandeld.', unavailablePrefix:'AI-tutor niet beschikbaar' }
  }

  function words(s) { var o = {}; var a = s.split(/\s+/); for (var i=0;i<a.length;i++) if(a[i]) o[a[i]]=true; return o }
  function normalizeLanguage(v) { v = String(v || 'english').toLowerCase(); if (v === 'es' || v === 'es-419' || v === 'spanish-latam') return 'spanish'; if (v === 'fr') return 'french'; if (v === 'de') return 'german'; if (v === 'pt' || v === 'pt-br') return 'portuguese'; if (v === 'it') return 'italian'; if (v === 'nl') return 'dutch'; return LANG[v] ? v : 'english' }
  function mergeStrings(lang) { var base = STRINGS.english; var ext = STRINGS[lang] || {}; var runtime = (window.__CS_AI_TUTOR_STRINGS__ && window.__CS_AI_TUTOR_STRINGS__[lang]) || {}; var out = {}; for (var k in base) out[k] = base[k]; for (var e in ext) out[e] = ext[e]; for (var r in runtime) out[r] = runtime[r]; return out }
  function txt(key) { return (state.strings && state.strings[key]) || STRINGS.english[key] || key }

  var state = { initialized:false, panelOpen:false, loadingBundle:false, bundleReady:false, bundle:null, history:[], currentModule:CFG.moduleNumber || 1, currentLesson:CFG.lessonTitle || null, moduleScopeOnly:false, fatal:null, matchThreshold:DEFAULT_MATCH_THRESHOLD, answerWeight:DEFAULT_ANSWER_WEIGHT, phraseTerms:[], synonymPhrases:[], synonyms:null, language:normalizeLanguage(CFG.language || 'english'), strings:null, returnFocus:null, backgroundState:[], bodyOverflow:null }
  state.strings = mergeStrings(state.language)

  function el(tag, attrs, children) { var e=document.createElement(tag); attrs=attrs||{}; for(var k in attrs){ if(k==='class') e.className=attrs[k]; else if(k==='text') e.textContent=attrs[k]; else if(k.indexOf('data-')===0||k.indexOf('aria-')===0||k==='role'||k==='id'||k==='type'||k==='name'||k==='placeholder'||k==='autocomplete'||k==='tabindex'||k==='inert') e.setAttribute(k, attrs[k]); else if((k==='disabled'||k==='checked')&&attrs[k]) e.setAttribute(k,k) } if(children){ if(Array.isArray(children)){ for(var i=0;i<children.length;i++) if(children[i]!=null) e.appendChild(children[i]) } else if(typeof children==='string') e.textContent=children; else e.appendChild(children) } return e }

  function boot(){ if(state.initialized) return; state.initialized=true; try{ var raw=sessionStorage.getItem(SS_KEY_HISTORY); if(raw){ var parsed=JSON.parse(raw); if(parsed && Array.isArray(parsed.history)) state.history=parsed.history.slice(-MAX_HISTORY_EXCHANGES*2) } }catch(e){} document.addEventListener('keydown',onDialogKeydown); renderButton() }
  function renderButton(){ if(document.getElementById(DOM.button)) return; var btn=el('button',{id:DOM.button,class:'cs-tutor-fab',type:'button','aria-label':txt('openTutor'),'aria-haspopup':'dialog','aria-controls':DOM.panel,'aria-expanded':'false'}); btn.appendChild(el('span',{class:'cs-tutor-fab-icon','aria-hidden':'true',text:'✦'})); btn.appendChild(el('span',{class:'cs-tutor-fab-label',text:txt('askTutor')})); btn.addEventListener('click',openPanel); document.body.appendChild(btn) }
  function renderPanel(){ if(document.getElementById(DOM.panel)) return; var overlay=el('div',{id:DOM.overlay,class:'cs-tutor-overlay','aria-hidden':'true'}); overlay.addEventListener('click',closePanel); var panel=el('aside',{id:DOM.panel,class:'cs-tutor-panel',role:'dialog','aria-labelledby':DOM.title,'aria-modal':'true','aria-hidden':'true',inert:''}); var header=el('header',{class:'cs-tutor-header'}); header.appendChild(el('h2',{id:DOM.title,class:'cs-tutor-title',text:txt('title')})); var closeBtn=el('button',{id:DOM.closeBtn,class:'cs-tutor-close',type:'button','aria-label':txt('closeTutor')},'×'); closeBtn.addEventListener('click',closePanel); header.appendChild(closeBtn); panel.appendChild(header); var scopeRow=el('div',{class:'cs-tutor-scope'}); var scopeLbl=el('label',{class:'cs-tutor-scope-label'}); var scopeChk=el('input',{id:DOM.moduleToggle,type:'checkbox',class:'cs-tutor-scope-checkbox'}); scopeChk.addEventListener('change',function(){state.moduleScopeOnly=!!scopeChk.checked}); scopeLbl.appendChild(scopeChk); scopeLbl.appendChild(document.createTextNode(' '+txt('searchCurrentModuleOnly'))); scopeRow.appendChild(scopeLbl); panel.appendChild(scopeRow); var log=el('div',{id:DOM.log,class:'cs-tutor-log',role:'log','aria-live':'polite','aria-relevant':'additions'}); panel.appendChild(log); var status=el('div',{id:DOM.status,class:'cs-tutor-status',role:'status','aria-live':'polite','aria-atomic':'true'}); panel.appendChild(status); var form=el('form',{id:DOM.form,class:'cs-tutor-form'}); var input=el('input',{id:DOM.input,type:'text',class:'cs-tutor-input',placeholder:txt('inputPlaceholder'),autocomplete:'off','aria-label':txt('inputLabel')}); var submit=el('button',{id:DOM.submit,type:'submit',class:'cs-tutor-submit'},txt('ask')); form.appendChild(input); form.appendChild(submit); form.addEventListener('submit',onSubmit); panel.appendChild(form); var footer=el('div',{class:'cs-tutor-footer'}); footer.appendChild(el('span',{text:txt('footer')})); panel.appendChild(footer); document.body.appendChild(overlay); document.body.appendChild(panel); if(state.history.length===0 && !sessionStorage.getItem(SS_KEY_WELCOMED)) renderWelcome(log); else for(var i=0;i<state.history.length;i++) appendMessage(log,state.history[i]) }
  function renderWelcome(log){ var card=el('div',{id:DOM.welcome,class:'cs-tutor-welcome'}); card.appendChild(el('h3',{class:'cs-tutor-welcome-title',text:txt('welcomeTitle')})); card.appendChild(el('p',{class:'cs-tutor-welcome-body',text:txt('welcomeBody')})); var ok=el('button',{id:DOM.welcomeOk,class:'cs-tutor-welcome-ok',type:'button'},txt('gotIt')); ok.addEventListener('click',function(){ try{sessionStorage.setItem(SS_KEY_WELCOMED,'1')}catch(e){} if(card.parentNode) card.parentNode.removeChild(card); var input=document.getElementById(DOM.input); if(input && !state.fatal) input.focus() }); card.appendChild(ok); log.appendChild(card) }
  function getFocusable(panel){ var nodes=panel.querySelectorAll('button:not([disabled]), input:not([disabled]), [href], [tabindex]:not([tabindex="-1"])'); var out=[]; for(var i=0;i<nodes.length;i++){ if(nodes[i].getAttribute('aria-hidden')!=='true' && !nodes[i].hasAttribute('inert')) out.push(nodes[i]) } return out }
  function setBackgroundModalState(active){ if(active){ state.backgroundState=[]; state.bodyOverflow=document.body.style.overflow; var children=document.body.children; for(var i=0;i<children.length;i++){ var node=children[i]; if(node.id===DOM.panel||node.id===DOM.overlay) continue; state.backgroundState.push({node:node,hadInert:node.hasAttribute('inert'),ariaHidden:node.getAttribute('aria-hidden')}); node.setAttribute('inert',''); node.setAttribute('aria-hidden','true') } document.body.style.overflow='hidden'; return } for(var j=0;j<state.backgroundState.length;j++){ var saved=state.backgroundState[j]; if(!saved.node || !saved.node.isConnected) continue; if(!saved.hadInert) saved.node.removeAttribute('inert'); if(saved.ariaHidden===null) saved.node.removeAttribute('aria-hidden'); else saved.node.setAttribute('aria-hidden',saved.ariaHidden) } state.backgroundState=[]; document.body.style.overflow=state.bodyOverflow===null?'':state.bodyOverflow; state.bodyOverflow=null }
  function onDialogKeydown(event){ if(!state.panelOpen) return; var panel=document.getElementById(DOM.panel); if(!panel) return; if(event.key==='Escape'){ event.preventDefault(); closePanel(); return } if(event.key!=='Tab') return; var focusable=getFocusable(panel); if(!focusable.length){ event.preventDefault(); return } var first=focusable[0], last=focusable[focusable.length-1], active=document.activeElement; if(event.shiftKey && active===first){ event.preventDefault(); last.focus() } else if(!event.shiftKey && active===last){ event.preventDefault(); first.focus() } else if(!panel.contains(active)){ event.preventDefault(); first.focus() } }
  function openPanel(){ if(state.panelOpen) return; renderPanel(); var panel=document.getElementById(DOM.panel), overlay=document.getElementById(DOM.overlay), button=document.getElementById(DOM.button); if(!panel) return; state.returnFocus=document.activeElement; panel.removeAttribute('inert'); panel.setAttribute('aria-hidden','false'); panel.classList.add('cs-tutor-panel--open'); if(overlay) overlay.classList.add('cs-tutor-overlay--open'); if(button) button.setAttribute('aria-expanded','true'); state.panelOpen=true; setBackgroundModalState(true); var input=document.getElementById(DOM.input), closeBtn=document.getElementById(DOM.closeBtn); if(input && !state.fatal) input.focus(); else if(closeBtn) closeBtn.focus(); if(!state.bundleReady && !state.loadingBundle && !state.fatal) loadBundle() }
  function closePanel(){ if(!state.panelOpen) return; var panel=document.getElementById(DOM.panel), overlay=document.getElementById(DOM.overlay), button=document.getElementById(DOM.button), returnTarget=state.returnFocus; if(panel){ panel.classList.remove('cs-tutor-panel--open'); panel.setAttribute('aria-hidden','true'); panel.setAttribute('inert','') } if(overlay) overlay.classList.remove('cs-tutor-overlay--open'); if(button) button.setAttribute('aria-expanded','false'); state.panelOpen=false; setBackgroundModalState(false); state.returnFocus=null; if(returnTarget && returnTarget.isConnected && typeof returnTarget.focus==='function') returnTarget.focus(); else if(button) button.focus() }
  function setStatus(text){ var s=document.getElementById(DOM.status); if(s) s.textContent=text||'' }
  function setFatal(message){ state.fatal=message; var s=document.getElementById(DOM.status); if(s){s.textContent=''; s.appendChild(el('div',{class:'cs-tutor-fatal'},message))} var input=document.getElementById(DOM.input), submit=document.getElementById(DOM.submit); if(input) input.setAttribute('disabled','disabled'); if(submit) submit.setAttribute('disabled','disabled') }

  function loadBundle(){ if(state.loadingBundle||state.bundleReady||state.fatal) return; state.loadingBundle=true; setStatus(txt('loading')); if(window.__CS_AI_TUTOR_DATA__){ finishLoad(window.__CS_AI_TUTOR_DATA__); return } var s=document.createElement('script'); s.src=CFG.bundleUrl; s.async=true; s.onload=function(){ if(window.__CS_AI_TUTOR_DATA__) finishLoad(window.__CS_AI_TUTOR_DATA__); else { state.loadingBundle=false; setFatal(txt('unavailablePrefix')+': course Q&A data did not initialise correctly.') } }; s.onerror=function(){ state.loadingBundle=false; setFatal(txt('unavailablePrefix')+': failed to load course Q&A data.') }; document.head.appendChild(s) }
  function finishLoad(bundle){ if(!bundle || (bundle.bundle_version!==1 && bundle.bundle_version!==2 && bundle.bundle_version!==3)){ state.loadingBundle=false; setFatal(txt('unavailablePrefix')+': unsupported bundle version ('+(bundle&&bundle.bundle_version)+').'); return } state.language=normalizeLanguage(bundle.ui_language||bundle.language||CFG.language||state.language); state.strings=bundle.localized_strings || mergeStrings(state.language); updateVisibleStrings(); state.matchThreshold=(typeof CFG.matchThreshold==='number')?CFG.matchThreshold:(typeof bundle.match_threshold==='number')?bundle.match_threshold:DEFAULT_MATCH_THRESHOLD; state.answerWeight=(typeof CFG.answerWeight==='number')?CFG.answerWeight:(typeof bundle.answer_weight==='number')?bundle.answer_weight:DEFAULT_ANSWER_WEIGHT; state.phraseTerms=[]; if(Array.isArray(bundle.phrase_boost_terms)) for(var pi=0;pi<bundle.phrase_boost_terms.length;pi++){var pt=bundle.phrase_boost_terms[pi]; if(typeof pt==='string' && pt.indexOf(' ')>=0) state.phraseTerms.push(normalizePhraseText(pt))} state.synonymPhrases=Array.isArray(bundle.synonym_phrases)?bundle.synonym_phrases:[]; state.synonyms=normalizeSynonyms(bundle.synonyms); var pairs=bundle.pairs||[]; for(var i=0;i<pairs.length;i++){ var p=pairs[i]; var candidates=[p.question]; if(p.question_variants) for(var j=0;j<p.question_variants.length;j++) candidates.push(p.question_variants[j]); p._tokens=[]; for(var k=0;k<candidates.length;k++) p._tokens.push(tokenize(candidates[k])); p._answerTokens=tokenize(p.answer||''); var hay=[p.question||'']; if(p.question_variants) for(var h=0;h<p.question_variants.length;h++) hay.push(p.question_variants[h]); hay.push(p.answer||''); p._phraseHaystack=normalizePhraseText(hay.join(' ')); p._normQuestion=normalizePhraseText(p.question||'') } state.bundle=bundle; state.bundleReady=true; state.loadingBundle=false; setStatus(''); emitAnalytics('initialized',{pair_count:pairs.length,module_number:state.currentModule,match_threshold:state.matchThreshold,answer_weight:state.answerWeight,language:state.language,phrase_terms:state.phraseTerms.length,synonyms:state.synonyms?Object.keys(state.synonyms).length:0}) }
  function updateVisibleStrings(){ var b=document.getElementById(DOM.button); if(b){ b.setAttribute('aria-label',txt('openTutor')); var lbl=b.querySelector('.cs-tutor-fab-label'); if(lbl) lbl.textContent=txt('askTutor') } var title=document.getElementById(DOM.title); if(title) title.textContent=txt('title'); var closeBtn=document.getElementById(DOM.closeBtn); if(closeBtn) closeBtn.setAttribute('aria-label',txt('closeTutor')); var input=document.getElementById(DOM.input); if(input){ input.setAttribute('placeholder',txt('inputPlaceholder')); input.setAttribute('aria-label',txt('inputLabel')) } var submit=document.getElementById(DOM.submit); if(submit) submit.textContent=txt('ask') }

  function foldAccents(s){ try{return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'')}catch(e){return s} }
  function normalizePhraseText(s){ if(!s) return ''; var lang=LANG[state.language]||LANG.english; var x=String(s).toLowerCase(); if(lang.accent) x=foldAccents(x); return x.replace(/([\p{L}\p{N}])[-_/\\.]([\p{L}\p{N}])/gu,'$1 $2').replace(/[^\p{L}\p{N}+#.:-]+/gu,' ').replace(/^ +| +$/g,'').replace(/ +/g,' ') }
  function stem(t){ var lang=LANG[state.language]||LANG.english; if(!lang.stem) return t; if(!t||t.length<=3)return t; if(t.length>4&&t.substring(t.length-3)==='ies')return t.substring(0,t.length-3)+'y'; if(t.length>4&&t.substring(t.length-2)==='es'){var pre=t.substring(t.length-4,t.length-2),c=t.charAt(t.length-3); if(pre==='sh'||pre==='ch'||pre==='ss'||c==='x'||c==='z')return t.substring(0,t.length-2)} if(t.length>3&&t.charAt(t.length-1)==='s'){var tail=t.substring(t.length-2),tail3=t.length>=3?t.substring(t.length-3):''; if(tail!=='ss'&&tail!=='us'&&tail!=='is'&&tail!=='ys'&&tail3!=='ous')return t.substring(0,t.length-1)} if(t.length>5&&t.substring(t.length-3)==='ing')return t.substring(0,t.length-3); if(t.length>4&&t.substring(t.length-2)==='ed')return t.substring(0,t.length-2); return t }
  function tokenize(text){ if(!text)return[]; var lang=LANG[state.language]||LANG.english; var spaced=normalizePhraseText(text); var raw=spaced.split(/\s+/), out=[]; for(var i=0;i<raw.length;i++){var t=raw[i]; if(t.length<2)continue; if(lang.stop[t])continue; t=stem(t); if(t.length>=2&&!lang.stop[t])out.push(t)} return out }
  function normalizeSynonyms(src){ if(!src || typeof src!=='object') return null; var out={}, keys=Object.keys(src); for(var i=0;i<keys.length;i++){var kt=tokenize(keys[i])[0]; if(!kt)continue; var vals=src[keys[i]]; if(!Array.isArray(vals))continue; var arr=[]; for(var j=0;j<vals.length;j++){var vt=tokenize(vals[j])[0]; if(vt && vt!==kt)arr.push(vt)} if(arr.length)out[kt]=dedupe(arr)} return Object.keys(out).length?out:null }
  function dedupe(a){var s={},o=[]; for(var i=0;i<a.length;i++){if(!s[a[i]]){s[a[i]]=true;o.push(a[i])}} return o}
  function expandWithSynonyms(qTokens){ if(!state.synonyms)return qTokens; var seen={},out=[]; function add(t){if(!seen[t]){seen[t]=true;out.push(t)}} for(var i=0;i<qTokens.length;i++){add(qTokens[i]); var syns=state.synonyms[qTokens[i]]; if(syns) for(var j=0;j<syns.length;j++) add(syns[j])} return out }
  function jaccard(a,b){ if(!a.length||!b.length)return 0; var sa={},sb={},u={},inter=0,k; for(var i=0;i<a.length;i++){sa[a[i]]=true;u[a[i]]=true} for(var j=0;j<b.length;j++){sb[b[j]]=true;u[b[j]]=true} for(k in sa) if(sb[k]) inter++; var uc=0; for(k in u)uc++; return uc?inter/uc:0 }
  function coverageScore(qTokens,pTokens,idfMap,defaultIdf){ if(!qTokens.length||!pTokens.length)return 0; if(!idfMap)return jaccard(qTokens,pTokens); var pSet={},qSet={},qTotal=0,matched=0,t,w; for(var j=0;j<pTokens.length;j++)pSet[pTokens[j]]=true; for(var i=0;i<qTokens.length;i++)qSet[qTokens[i]]=true; for(t in qSet){w=idfMap[t]; if(w===undefined)w=defaultIdf; qTotal+=w; if(pSet[t])matched+=w} return qTotal?matched/qTotal:0 }
  function phraseBoost(normQuery,pairHaystack){ if(!normQuery||!pairHaystack)return 0; var bonus=0; for(var i=0;i<state.phraseTerms.length;i++){var phrase=state.phraseTerms[i]; if(normQuery.indexOf(phrase)>=0&&pairHaystack.indexOf(phrase)>=0){bonus+=PHRASE_TERM_BOOST;if(bonus>=PHRASE_TERM_BOOST_CAP)return PHRASE_TERM_BOOST_CAP}} for(var j=0;j<state.synonymPhrases.length;j++){var sp=state.synonymPhrases[j]; var canon=normalizePhraseText(sp.canonical||''); var alts=sp.alternatives||[]; for(var k=0;k<alts.length;k++){var alt=normalizePhraseText(alts[k]); if(((normQuery.indexOf(canon)>=0&&pairHaystack.indexOf(alt)>=0)||(normQuery.indexOf(alt)>=0&&pairHaystack.indexOf(canon)>=0))){bonus+=PHRASE_TERM_BOOST;if(bonus>=PHRASE_TERM_BOOST_CAP)return PHRASE_TERM_BOOST_CAP}}} return bonus }
  function exactQuestionBoost(normQuery,normQuestion){ if(!normQuery||!normQuestion)return 0; if(normQuestion.length>=6&&normQuery.indexOf(normQuestion)>=0)return EXACT_PHRASE_BOOST; if(normQuery.length>=6&&normQuestion.indexOf(normQuery)>=0)return EXACT_PHRASE_BOOST; return 0 }
  function rerank(scored){ for(var i=0;i<scored.length;i++){var sp=scored[i]; if(sp.module_number===state.currentModule)sp.score+=MODULE_BOOST_CURRENT; else if(sp.module_number>state.currentModule)sp.score-=MODULE_PENALTY_FUTURE; if(state.currentLesson&&sp.source_lesson===state.currentLesson)sp.score+=LESSON_BOOST} scored.sort(function(a,b){return b.score-a.score}); return scored }
  function searchBundle(query){ if(!state.bundle)return null; var raw=tokenize(query); if(!raw.length)return null; var qTokens=expandWithSynonyms(raw); var normQuery=normalizePhraseText(query); var pairs=state.bundle.pairs||[], idfMap=state.bundle.idf_map||null, N=pairs.length||100, defaultIdf=Math.log(N+1)+1, scored=[]; for(var i=0;i<pairs.length;i++){var p=pairs[i]; if(state.moduleScopeOnly&&p.module_number!==state.currentModule)continue; var best=0; for(var j=0;j<p._tokens.length;j++){var s=coverageScore(qTokens,p._tokens[j],idfMap,defaultIdf); if(s>best)best=s} if(state.answerWeight>0&&p._answerTokens&&p._answerTokens.length){var aScore=coverageScore(qTokens,p._answerTokens,idfMap,defaultIdf)*state.answerWeight; if(aScore>best)best=aScore} best+=phraseBoost(normQuery,p._phraseHaystack); best+=exactQuestionBoost(normQuery,p._normQuestion); scored.push({score:best,id:p.id,question:p.question,answer:p.answer,module_number:p.module_number,source_lesson:p.source_lesson,category:p.category}) } if(!scored.length)return null; return rerank(scored)[0] }
  function onSubmit(e){ e.preventDefault(); if(state.fatal)return; var input=document.getElementById(DOM.input), query=(input.value||'').trim(); if(!query)return; if(!state.bundleReady){setStatus(txt('loadingWait'));return} input.value=''; var log=document.getElementById(DOM.log), w=document.getElementById(DOM.welcome); if(w&&w.parentNode)w.parentNode.removeChild(w); var userMsg={role:'user',text:query,ts:Date.now()}; pushHistory(userMsg); appendMessage(log,userMsg); var match=searchBundle(query), threshold=state.matchThreshold; if(!match||match.score<threshold){var refusal={role:'assistant',text:txt('refusal'),ts:Date.now()}; pushHistory(refusal); appendMessage(log,refusal); emitAnalytics('no_match',{module_number:state.currentModule,top_score:match?Number(match.score.toFixed(4)):0,threshold:Number(threshold.toFixed(4)),language:state.language}); return} var answerMsg={role:'assistant',text:match.answer,citation:buildCitation(match),ts:Date.now()}; pushHistory(answerMsg); appendMessage(log,answerMsg); emitAnalytics('answered',{module_number:state.currentModule,matched_id:match.id,matched_module:match.module_number,category:match.category,score:Number(match.score.toFixed(4)),is_cross_module:match.module_number!==state.currentModule,language:state.language}) }
  function buildCitation(match){ var titleMap=(state.bundle&&state.bundle.module_titles)||{}, modTitle=titleMap[match.module_number]||('Module '+match.module_number), lesson=match.source_lesson?(' — '+match.source_lesson):'', prefix=txt('fromModule')+' '+match.module_number+': '+modTitle+lesson; if(match.module_number===state.currentModule)return prefix; if(match.module_number>state.currentModule)return prefix+'. ('+txt('laterInCourse')+')'; return prefix+'. ('+txt('earlierInCourse')+')' }
  function pushHistory(msg){ state.history.push(msg); while(state.history.length>MAX_HISTORY_EXCHANGES*2)state.history.shift(); try{sessionStorage.setItem(SS_KEY_HISTORY,JSON.stringify({v:5,history:state.history}))}catch(e){} }
  function appendMessage(log,msg){ if(!log)return; var row=el('div',{class:'cs-tutor-msg cs-tutor-msg--'+msg.role}); row.appendChild(el('div',{class:'cs-tutor-msg-body',text:msg.text})); if(msg.citation)row.appendChild(el('div',{class:'cs-tutor-citation',text:msg.citation})); log.appendChild(row); log.scrollTop=log.scrollHeight }
  function emitAnalytics(verb,details){ try{ if(typeof window.CS_xAPI_sendStatement==='function') window.CS_xAPI_sendStatement({verb:verb,object:'ai_tutor',details:details||{}}) }catch(e){} }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot); else boot()
})()
